class Constants {
  static const Map<String, List<Map<String, dynamic>>> allTypes = {
    "Accounting": [
      {
        'id': 'basic',
        'title': 'Basic Accounting Principles',
        'tier': 'free',
        'topics': [
          "Accounting Equation (Assets = Liabilities + Equity)",
          "Double-Entry System",
          "Accrual & Cash Accounting",
          "GAAP & IFRS",
        ],
      },
      {
        'id': 'finan',
        'title': 'Financial Statements',
        'tier': 'free',
        'topics': [
          "Balance Sheet",
          "Income Statement (Profit & Loss)",
          "Cash Flow Statement",
          "Statement of Changes in Equity",
        ],
      },
      {
        'id': 'conce',
        'title': 'Accounting Concepts & Terminologies',
        'tier': 'free',
        'topics': [
          "Assets, Liabilities, and Equity",
          "Revenue & Expenses",
          "Depreciation & Amortization",
          "Trial Balance & Adjustments",
        ],
      },
      {
        'id': 'journ',
        'title': 'Journal Entries & Ledgers',
        'tier': 'free',
        'topics': [
          "Recording Transactions",
          "General Ledger & Subsidiary Ledgers",
          "T-Accounts",
          "Adjusting & Closing Entries",
        ],
      },
      {
        'id': 'cost',
        'title': 'Cost & Managerial Accounting',
        'tier': 'free',
        'topics': [
          "Fixed vs. Variable Costs",
          "Break-Even Analysis",
          "Budgeting & Forecasting",
          "Marginal Costing",
        ],
      },
      {
        'id': 'audit',
        'title': 'Auditing & Internal Controls',
        'tier': 'vip',
        'topics': [
          "Types of Audits (Internal, External, Forensic)",
          "Audit Procedures & Risk Assessment",
          "Fraud Detection & Prevention",
          "Compliance & Ethics",
        ],
      },
      {
        'id': 'tax',
        'title': 'Taxation',
        'tier': 'vip',
        'topics': [
          "Direct vs. Indirect Taxes",
          "GST/VAT Basics",
          "Corporate & Income Tax",
          "Tax Deductions & Allowances",
        ],
      },
      {
        'id': 'ratio',
        'title': 'Financial Ratios & Analysis',
        'tier': 'vip',
        'topics': [
          "Liquidity Ratios (Current Ratio, Quick Ratio)",
          "Profitability Ratios (ROA, ROE, Gross Margin)",
          "Solvency Ratios (Debt-to-Equity)",
          "Efficiency Ratios (Asset Turnover)",
        ],
      },
    ],
    "SAP": [
      {
        'id': 'intro',
        'title': 'Introduction to SAP ERP',
        'tier': 'free',
        'topics': [
          "Overview of SAP & Modules",
          "SAP FICO (Finance & Controlling) Introduction",
          "SAP Interface & Navigation",
          "Master Data (Customer, Vendor, GL Accounts)",
        ],
      },
      {
        'id': 'fi',
        'title': 'SAP Financial Accounting (FI)',
        'tier': 'free',
        'topics': [
          "General Ledger (GL) Accounting",
          "Accounts Payable & Receivable (AP/AR)",
          "Asset Accounting (AA)",
          "Bank Accounting & Reconciliation",
        ],
      },
      {
        'id': 'co',
        'title': 'SAP Controlling (CO)',
        'tier': 'free',
        'topics': [
          "Cost Element & Cost Center Accounting",
          "Internal Orders & Profit Center Accounting",
          "Budgeting & Forecasting",
          "Activity-Based Costing (ABC)",
        ],
      },
      {
        'id': 'sapt',
        'title': 'SAP Taxation & Compliance',
        'tier': 'vip',
        'topics': [
          "GST/VAT in SAP",
          "Withholding Tax & TDS",
          "SAP Payroll & Tax Deductions",
          "SAP Financial Reports & Compliance",
        ],
      },
      {
        'id': 'adv',
        'title': 'Advanced SAP Features',
        'tier': 'vip',
        'topics': [
          "SAP Integration with Other Modules (MM, SD)",
          "SAP HANA vs. Traditional SAP",
          "Financial Reporting & Business Intelligence",
          "SAP Automation & Customization (ABAP Basics)",
        ],
      },
    ],
    "Tally": [
      {
        'id': 'tal_bas',
        'title': 'Basics of Tally',
        'tier': 'free',
        'topics': [
          "Introduction to Tally ERP & Tally Prime",
          "Features & Advantages of Tally",
          "Setting Up Company in Tally",
          "Navigation & Shortcuts",
        ],
      },
      {
        'id': 'ac_tally',
        'title': 'Accounting in Tally',
        'tier': 'free',
        'topics': [
          "Ledger & Group Creation",
          "Vouchers (Payment, Receipt, Contra, Journal)",
          "Bank Reconciliation in Tally",
          "Adjustments & Closing Entries",
        ],
      },
      {
        'id': 'inv',
        'title': 'Inventory Management',
        'tier': 'free',
        'topics': [
          "Stock Groups",
          "Categories & Units",
          "Stock Items & BOM (Bill of Materials)",
          "Godown & Warehouse Management",
          "Inventory Valuation Methods",
        ],
      },
      {
        'id': 'taxa',
        'title': 'Taxation in Tally',
        'tier': 'vip',
        'topics': [
          "GST Setup & Compliance",
          "VAT, TDS, TCS Entries",
          "Payroll & Income Tax in Tally",
          "Filing GST Returns through Tally",
        ],
      },
      {
        'id': 'eco',
        'title': 'Tally Advanced Features',
        'tier': 'vip',
        'topics': [
          "Cost Centers & Budgeting",
          "Multi-Currency Transactions",
          "Security & User Management",
          "Tally ODBC & Data Synchronization",
        ],
      },
    ],
    "ACCA": [
      {
        'id': 'acca_bt',
        'title': 'Business and Technology (BT)',
        'tier': 'free',
        'topics': [
          "Business Organisation & Structure",
          "Stakeholders & External Environment",
          "Accounting Systems & Controls",
          "Professional Ethics in Business",
        ],
      },
      {
        'id': 'acca_ma',
        'title': 'Management Accounting (MA)',
        'tier': 'free',
        'topics': [
          "Cost Classification & Accounting",
          "Overhead Absorption Costing",
          "Budgeting & Standard Costing",
          "Marginal vs Absorption Costing",
          "Performance Measurement",
        ],
      },
      {
        'id': 'acca_fa',
        'title': 'Financial Accounting (FA)',
        'tier': 'free',
        'topics': [
          "Double-Entry Bookkeeping",
          "Recording Transactions & Events",
          "Trial Balance & Financial Statements",
          "Consolidated Financial Statements",
          "Interpretation of Financial Statements",
        ],
      },
      {
        'id': 'acca_lw',
        'title': 'Corporate and Business Law (LW)',
        'tier': 'free',
        'topics': [
          "Essential Elements of Legal System",
          "Law of Obligations (Contract & Torts)",
          "Employment Law",
          "Formation & Constitution of Companies",
          "Capital & Financing of Companies",
        ],
      },
      {
        'id': 'acca_pm',
        'title': 'Performance Management (PM)',
        'tier': 'free',
        'topics': [
          "Specialist Cost Techniques",
          "Decision-Making Techniques",
          "Budgeting & Control Systems",
          "Standard Costing & Variances",
          "Performance Measurement & Control",
        ],
      },
      {
        'id': 'acca_tx',
        'title': 'Taxation (TX)',
        'tier': 'vip',
        'topics': [
          "UK Tax System & Administration",
          "Income Tax & National Insurance",
          "Chargeable Gains for Individuals",
          "Corporation Tax Liabilities",
          "Value Added Tax (VAT)",
        ],
      },
      {
        'id': 'acca_fr',
        'title': 'Financial Reporting (FR)',
        'tier': 'vip',
        'topics': [
          "Conceptual Framework for Reporting",
          "Accounting for Transactions",
          "Consolidated Financial Statements",
          "IFRS Standards (IAS 16, 36, 37)",
          "Financial Statement Analysis",
        ],
      },
      {
        'id': 'acca_aa',
        'title': 'Audit and Assurance (AA)',
        'tier': 'vip',
        'topics': [
          "Audit Framework & Regulation",
          "Planning & Conducting an Audit",
          "Internal Control & Audit Evidence",
          "Review & Reporting on Audit",
        ],
      },
      {
        'id': 'acca_fm',
        'title': 'Financial Management (FM)',
        'tier': 'vip',
        'topics': [
          "Financial Management Function",
          "Working Capital Management",
          "Investment Appraisal",
          "Business Finance & Cost of Capital",
          "Risk Management",
        ],
      },
      {
        'id': 'acca_sbl',
        'title': 'Strategic Business Leader (SBL)',
        'tier': 'vip',
        'topics': [
          "Leadership & Governance",
          "Strategic Planning & Implementation",
          "Risk Management & Technology",
          "Organizational Control & Audit",
          "Innovation & Change Management",
        ],
      },
      {
        'id': 'acca_sbr',
        'title': 'Strategic Business Reporting (SBR)',
        'tier': 'vip',
        'topics': [
          "Ethical & Professional Principles",
          "Financial Reporting Framework",
          "Group Financial Statements",
          "Changes in Accounting Regulation",
          "Current Developments in Reporting",
        ],
      },
      {
        'id': 'acca_afm',
        'title': 'Advanced Financial Management (AFM)',
        'tier': 'vip',
        'topics': [
          "Advanced Investment Appraisal",
          "Acquisitions & Mergers",
          "Corporate Reconstruction",
          "Treasury & Risk Management",
          "Ethical Issues in Finance",
        ],
      },
      {
        'id': 'acca_apm',
        'title': 'Advanced Performance Management (APM)',
        'tier': 'vip',
        'topics': [
          "Strategic Planning & Control",
          "Performance Management in Digital Enterprise",
          "External Influences on Performance",
          "Strategic Performance Measurement",
          "Performance Measurement Systems",
        ],
      },
      {
        'id': 'acca_aaa',
        'title': 'Advanced Audit and Assurance (AAA)',
        'tier': 'vip',
        'topics': [
          "Regulatory Environment & Ethics",
          "Practice Management & Quality Control",
          "Audit of Group Financial Statements",
          "Other Assignments (Forensic, Internal)",
          "Reporting & Current Developments",
        ],
      },
    ],
    "CMA (USA)": [
      {
        'id': 'cma_ext',
        'title': 'External Financial Reporting',
        'tier': 'free',
        'topics': [
          "Financial Statements",
          "Revenue Recognition",
          "Balance Sheet & Cash Flow Statement",
          "Income Statement & Comprehensive Income",
        ],
      },
      {
        'id': 'cma_plan',
        'title': 'Planning, Budgeting & Forecasting',
        'tier': 'free',
        'topics': [
          "Strategic Planning & Budgeting",
          "Annual Profit Plan & Schedules",
          "Forecasting Techniques",
          "Top-Level Planning & Analysis",
        ],
      },
      {
        'id': 'cma_perf',
        'title': 'Performance Management',
        'tier': 'free',
        'topics': [
          "Cost & Variance Measures",
          "Responsibility Centers",
          "Performance Measures",
          "Balanced Scorecard",
        ],
      },
      {
        'id': 'cma_cost',
        'title': 'Cost Management',
        'tier': 'free',
        'topics': [
          "Cost Measurement Systems",
          "Overhead Costs & Capacity",
          "Activity-Based Costing",
          "Supply Chain & Lean Principles",
        ],
      },
      {
        'id': 'cma_cont',
        'title': 'Internal Controls',
        'tier': 'vip',
        'topics': [
          "Governance, Risk & Compliance",
          "Internal Auditing",
          "System Controls",
          "Financial & IT Controls",
        ],
      },
      {
        'id': 'cma_tech',
        'title': 'Technology & Analytics',
        'tier': 'vip',
        'topics': [
          "Information Systems & Data Governance",
          "Technology-Enabled Finance",
          "Data Analytics",
          "Data Visualization",
        ],
      },
      {
        'id': 'cma_fsa',
        'title': 'Financial Statement Analysis',
        'tier': 'vip',
        'topics': [
          "Basic Financial Statement Analysis",
          "Profitability & Liquidity Ratios",
          "Solvency & Market Ratios",
          "Cash Flow Statement Analysis",
        ],
      },
      {
        'id': 'cma_corp',
        'title': 'Corporate Finance',
        'tier': 'vip',
        'topics': [
          "Risk & Return, Financial Instruments",
          "Cost of Capital",
          "Managing Current Assets",
          "Raising Capital & Restructuring",
        ],
      },
      {
        'id': 'cma_dec',
        'title': 'Decision Analysis',
        'tier': 'vip',
        'topics': [
          "Cost/Volume/Profit (CVP) Analysis",
          "Marginal Analysis",
          "Pricing Strategies",
          "Risk Management in Decisions",
        ],
      },
      {
        'id': 'cma_risk',
        'title': 'Risk Management',
        'tier': 'vip',
        'topics': [
          "Enterprise Risk Management (ERM)",
          "Financial Risk",
          "Operational Risk",
          "Strategic & Hazard Risk",
        ],
      },
      {
        'id': 'cma_inv',
        'title': 'Investment Decisions',
        'tier': 'vip',
        'topics': [
          "Capital Budgeting Process",
          "Discounted Cash Flow (DCF)",
          "Payback Method",
          "ROI Methods",
        ],
      },
      {
        'id': 'cma_eth',
        'title': 'Professional Ethics',
        'tier': 'vip',
        'topics': [
          "Ethical Considerations",
          "IMA's Ethical Professional Practice",
          "Fraud Prevention",
          "Ethical Resolution Practices",
        ],
      },
    ],
    "CMA (India)": [
      {
        'id': 'cma_ind_found',
        'title': 'CMA Foundation Level',
        'tier': 'free',
        'topics': [
          "Fundamentals of Accounting",
          "Business Laws and Ethics",
          "Business Economics",
          "Quantitative Techniques",
        ],
      },
      {
        'id': 'cma_ind_inter1',
        'title': 'CMA Intermediate - Group I',
        'tier': 'free',
        'topics': [
          "Financial Accounting",
          "Direct and Indirect Taxation",
          "Cost Accounting",
          "Computer Fundamentals",
        ],
      },
      {
        'id': 'cma_ind_inter2',
        'title': 'CMA Intermediate - Group II',
        'tier': 'free',
        'topics': [
          "Operation Management",
          "Financial Management",
          "Management Accounting and Financial Analysis",
          "Corporate Laws & Compliance",
        ],
      },
      {
        'id': 'cma_ind_final1',
        'title': 'CMA Final - Group I',
        'tier': 'vip',
        'topics': [
          "Strategic Financial Management",
          "Strategic Cost Management",
          "Corporate Financial Reporting",
          "Indirect Tax Laws and Practice",
        ],
      },
      {
        'id': 'cma_ind_final2',
        'title': 'CMA Final - Group II',
        'tier': 'vip',
        'topics': [
          "Direct Tax Laws and International Taxation",
          "Cost and Management Audit",
          "Strategic Performance Management",
          "Business Valuation and Risk Management",
        ],
      },
      {
        'id': 'cma_ind_cost',
        'title': 'Cost Accounting Standards',
        'tier': 'vip',
        'topics': [
          "Cost Accounting Standards (CAS)",
          "Material and Inventory Control",
          "Labour Cost Accounting",
          "Overhead Cost Allocation",
        ],
      },
      {
        'id': 'cma_ind_mgt',
        'title': 'Management Accounting & Strategy',
        'tier': 'vip',
        'topics': [
          "Budgetary Control",
          "Standard Costing",
          "Marginal Costing and Decision Making",
          "Strategic Management Accounting",
        ],
      },
      {
        'id': 'cma_ind_fin',
        'title': 'Financial Management & Policy',
        'tier': 'vip',
        'topics': [
          "Working Capital Management",
          "Capital Budgeting",
          "Financial Markets and Instruments",
          "Dividend Policy and Corporate Restructuring",
        ],
      },
      {
        'id': 'cma_ind_tax',
        'title': 'Direct & Indirect Taxation',
        'tier': 'vip',
        'topics': [
          "Income Tax for Individuals and Companies",
          "GST and Customs",
          "International Taxation",
          "Tax Planning and Management",
        ],
      },
      {
        'id': 'cma_ind_audit',
        'title': 'Internal Audit & Controls',
        'tier': 'vip',
        'topics': [
          "Internal Audit Framework",
          "Risk-Based Auditing",
          "Operational and Compliance Audits",
          "Audit Reporting and Documentation",
        ],
      },
      {
        'id': 'cma_ind_it',
        'title': 'IT & Analytics in Management',
        'tier': 'vip',
        'topics': [
          "ERP in Cost and Management Accounting",
          "Data Analytics for Decision Making",
          "Digital Transformation in Finance",
          "Cybersecurity and Data Protection",
        ],
      },
      {
        'id': 'cma_ind_ethics',
        'title': 'Professional Ethics',
        'tier': 'vip',
        'topics': [
          "Professional Code of Conduct",
          "Corporate Governance",
          "Ethical Decision Making",
          "Social Responsibility and Sustainability",
        ],
      },
    ],
    "CIMA (UK)": [
      {
        'id': 'cima_ba1',
        'title': 'BA1 - Fundamentals of Business Economics',
        'tier': 'free',
        'topics': [
          "Macroeconomic and Microeconomic Concepts",
          "Market Structures and Competition",
          "Global Business Environment",
          "Government Policies and Business",
        ],
      },
      {
        'id': 'cima_ba2',
        'title': 'BA2 - Fundamentals of Management Accounting',
        'tier': 'free',
        'topics': [
          "Cost Classification and Behaviour",
          "Budgeting and Forecasting",
          "Cost-Volume-Profit Analysis",
          "Performance Measurement",
        ],
      },
      {
        'id': 'cima_ba3',
        'title': 'BA3 - Fundamentals of Financial Accounting',
        'tier': 'free',
        'topics': [
          "Double-Entry Bookkeeping",
          "Preparation of Financial Statements",
          "Accounting for Partnerships and Companies",
          "Interpretation of Financial Statements",
        ],
      },
      {
        'id': 'cima_ba4',
        'title': 'BA4 - Fundamentals of Ethics, Governance & Law',
        'tier': 'free',
        'topics': [
          "Ethical Theories and Professional Ethics",
          "Corporate Governance",
          "Business Law and Contracts",
          "Employment and Company Law",
        ],
      },
      {
        'id': 'cima_e1',
        'title': 'E1 - Managing Finance in a Digital World',
        'tier': 'free',
        'topics': [
          "Digital Business Models",
          "Fintech and Digital Finance",
          "Data Analytics in Finance",
          "Digital Transformation Strategy",
        ],
      },
      {
        'id': 'cima_p1',
        'title': 'P1 - Management Accounting',
        'tier': 'vip',
        'topics': [
          "Cost Accounting Systems",
          "Budgetary Control",
          "Standard Costing and Variance Analysis",
          "Performance Management Systems",
        ],
      },
      {
        'id': 'cima_f1',
        'title': 'F1 - Financial Reporting',
        'tier': 'vip',
        'topics': [
          "Group Financial Statements",
          "Accounting for Business Combinations",
          "Financial Reporting Standards (IFRS)",
          "Analysis of Financial Performance",
        ],
      },
      {
        'id': 'cima_e2',
        'title': 'E2 - Managing Performance',
        'tier': 'vip',
        'topics': [
          "Project Management",
          "Change Management",
          "Organizational Performance Measurement",
          "Strategic Implementation",
        ],
      },
      {
        'id': 'cima_p2',
        'title': 'P2 - Advanced Management Accounting',
        'tier': 'vip',
        'topics': [
          "Advanced Costing Techniques",
          "Decision Making under Uncertainty",
          "Risk Management in Projects",
          "Advanced Budgetary Control",
        ],
      },
      {
        'id': 'cima_f2',
        'title': 'F2 - Advanced Financial Reporting',
        'tier': 'vip',
        'topics': [
          "Complex Group Structures",
          "Foreign Currency Transactions",
          "Financial Instruments Reporting",
          "Sustainability and Integrated Reporting",
        ],
      },
      {
        'id': 'cima_e3',
        'title': 'E3 - Strategic Management',
        'tier': 'vip',
        'topics': [
          "Strategic Analysis and Choice",
          "Strategic Implementation",
          "Strategic Control and Evaluation",
          "Global Strategic Management",
        ],
      },
      {
        'id': 'cima_p3',
        'title': 'P3 - Risk Management',
        'tier': 'vip',
        'topics': [
          "Enterprise Risk Management",
          "Financial Risk Management",
          "Operational Risk Management",
          "Risk Governance and Compliance",
        ],
      },
      {
        'id': 'cima_f3',
        'title': 'F3 - Financial Strategy',
        'tier': 'vip',
        'topics': [
          "Corporate Financial Strategy",
          "Mergers and Acquisitions",
          "Treasury Management",
          "International Financial Management",
        ],
      },
    ],
    "CPA": [
      {
        'id': 'cpa_aud',
        'title': 'Auditing and Attestation (AUD)',
        'tier': 'free',
        'topics': [
          "Ethics & Professional Responsibilities",
          "Assessing Risk & Planned Response",
          "Performing Procedures & Evidence",
          "Forming Conclusions & Reporting",
        ],
      },
      {
        'id': 'cpa_far',
        'title': 'Financial Accounting & Reporting (FAR)',
        'tier': 'free',
        'topics': [
          "Conceptual Framework & Standard-Setting",
          "Select Financial Statement Accounts",
          "Select Transactions",
          "State and Local Governments",
        ],
      },
      {
        'id': 'cpa_reg',
        'title': 'Regulation (REG)',
        'tier': 'vip',
        'topics': [
          "Ethics & Federal Tax Procedures",
          "Business Law",
          "Federal Taxation of Property",
          "Federal Taxation of Individuals & Entities",
        ],
      },
      {
        'id': 'cpa_bec',
        'title': 'Business Environment & Concepts (BEC)',
        'tier': 'vip',
        'topics': [
          "Corporate Governance",
          "Economic Concepts & Analysis",
          "Financial Management",
          "Information Technology",
          "Operations Management",
        ],
      },
    ],
    "GST": [
      {
        'id': 'gst_bas',
        'title': 'GST Basics and Concepts',
        'tier': 'free',
        'topics': [
          "Charge of GST, Supply, Levy & Collection",
          "Concept of Time, Place & Value of Supply",
          "Input Tax Credit (ITC)",
          "Composite vs Regular Scheme",
        ],
      },
      {
        'id': 'gst_reg',
        'title': 'Registration Procedures',
        'tier': 'free',
        'topics': [
          "Threshold Limits for Registration",
          "Compulsory Registration Cases",
          "Registration Procedure & Documentation",
          "Amendment & Cancellation of Registration",
        ],
      },
      {
        'id': 'gst_inv',
        'title': 'Invoicing under GST',
        'tier': 'free',
        'topics': [
          "Tax Invoice & Bill of Supply",
          "Receipt & Payment Voucher",
          "Credit & Debit Notes",
          "E-invoicing System & Compliance",
        ],
      },
      {
        'id': 'gst_ret',
        'title': 'Returns Filing',
        'tier': 'vip',
        'topics': [
          "GSTR-1 (Outward Supplies)",
          "GSTR-3B (Summary Return)",
          "GSTR-9 (Annual Return)",
          "GSTR-9C (Reconciliation Statement)",
        ],
      },
      {
        'id': 'gst_pay',
        'title': 'Payments and Refunds',
        'tier': 'vip',
        'topics': [
          "Modes of Payment (Online, Offline)",
          "TDS & TCS under GST",
          "Refund Procedure & Documentation",
          "Interest & Late Fees",
        ],
      },
      {
        'id': 'gst_aud',
        'title': 'Audit and Assessment',
        'tier': 'vip',
        'topics': [
          "Types of Audit (Departmental, Special)",
          "Self-Assessment Procedure",
          "Summary Assessment",
          "Best Judgment Assessment",
        ],
      },
    ],
    "CA (India)": [
      {
        'id': 'ca_found',
        'title': 'Foundation Level',
        'tier': 'free',
        'topics': [
          "Principles and Practice of Accounting",
          "Business Laws and Business Correspondence",
          "Business Mathematics and Statistics",
          "Business Economics and Business Commercial Knowledge",
        ],
      },
      {
        'id': 'ca_inter1',
        'title': 'Intermediate - Group I',
        'tier': 'free',
        'topics': [
          "Accounting",
          "Corporate and Other Laws",
          "Cost and Management Accounting",
          "Taxation",
        ],
      },
      {
        'id': 'ca_inter2',
        'title': 'Intermediate - Group II',
        'tier': 'vip',
        'topics': [
          "Advanced Accounting",
          "Auditing and Assurance",
          "Enterprise Information Systems and Strategic Management",
          "Financial Management and Economics for Finance",
        ],
      },
      {
        'id': 'ca_final1',
        'title': 'Final - Group I',
        'tier': 'vip',
        'topics': [
          "Financial Reporting",
          "Strategic Financial Management",
          "Advanced Auditing and Professional Ethics",
          "Corporate and Economic Laws",
        ],
      },
      {
        'id': 'ca_final2',
        'title': 'Final - Group II',
        'tier': 'vip',
        'topics': [
          "Strategic Cost Management and Performance Evaluation",
          "Elective Papers (Any One)",
          "Direct Tax Laws and International Taxation",
          "Indirect Tax Laws",
        ],
      },
    ],
    "CA (International)": [
      {
        'id': 'ca_int_found',
        'title': 'ICAEW Certificate Level',
        'tier': 'free',
        'topics': [
          "Accounting Principles and Concepts",
          "Business and Finance Fundamentals",
          "Management Information",
          "Law for Accountants",
        ],
      },
      {
        'id': 'ca_int_prof',
        'title': 'ICAEW Professional Level',
        'tier': 'free',
        'topics': [
          "Business Planning and Taxation",
          "Audit and Assurance",
          "Financial Accounting and Reporting",
          "Business Strategy and Technology",
        ],
      },
      {
        'id': 'ca_int_adv',
        'title': 'ICAEW Advanced Level',
        'tier': 'vip',
        'topics': [
          "Corporate Reporting",
          "Strategic Business Management",
          "Case Study Integration",
          "Advanced Financial Analysis",
        ],
      },
      {
        'id': 'ca_int_ifrs',
        'title': 'International Financial Reporting (IFRS)',
        'tier': 'vip',
        'topics': [
          "IFRS Framework and Standards",
          "Consolidated Financial Statements",
          "Accounting for Financial Instruments",
          "Revenue Recognition and Leases",
        ],
      },
      {
        'id': 'ca_int_audit',
        'title': 'International Auditing Standards',
        'tier': 'vip',
        'topics': [
          "International Standards on Auditing (ISA)",
          "Audit Planning and Risk Assessment",
          "Internal Control Evaluation",
          "Audit Evidence and Documentation",
        ],
      },
      {
        'id': 'ca_int_tax',
        'title': 'International Taxation Principles',
        'tier': 'vip',
        'topics': [
          "International Tax Principles",
          "Transfer Pricing",
          "Tax Treaties and Double Taxation",
          "BEPS and Global Tax Compliance",
        ],
      },
      {
        'id': 'ca_int_fin',
        'title': 'Corporate Finance International',
        'tier': 'vip',
        'topics': [
          "International Capital Markets",
          "Cross-Border Financing",
          "Foreign Exchange Risk Management",
          "International Investment Appraisal",
        ],
      },
      {
        'id': 'ca_int_strat',
        'title': 'Strategic Business Management',
        'tier': 'vip',
        'topics': [
          "Global Business Strategy",
          "International Market Entry",
          "Multinational Corporate Governance",
          "Global Supply Chain Management",
        ],
      },
      {
        'id': 'ca_int_ethics',
        'title': 'Global Professional Ethics',
        'tier': 'vip',
        'topics': [
          "International Code of Ethics",
          "Anti-Money Laundering (AML) Compliance",
          "Sustainability and ESG Reporting",
          "Whistleblowing and Corporate Governance",
        ],
      },
    ],
  };
}
